CREATE DATABASE QLNHAHANG
GO
USE QLNHAHANG
GO

--1. và 2. 

--Tạo các quan hệ cùng với khóa chính
CREATE TABLE NHAHANG(
	MANH CHAR(4) CONSTRAINT PK_NH PRIMARY KEY,
	TENNH VARCHAR(40),
	AMTHUC VARCHAR(20),
	MAVT CHAR(4),
	MADG CHAR(4)
)

CREATE TABLE VITRI(
	MAVT CHAR(4) CONSTRAINT PK_VT PRIMARY KEY,
	QUAN VARCHAR(40),
	THANHPHO VARCHAR(40)
)

CREATE TABLE DANHGIA (
	MADG CHAR(4) CONSTRAINT PK_DG PRIMARY KEY,
	DANHGIA FLOAT,
	GIATB MONEY,
	SLDG INT
)

--Tạo khóa ngoại cho các quan hệ
ALTER TABLE NHAHANG ADD CONSTRAINT FK_VT FOREIGN KEY (MAVT) REFERENCES VITRI(MAVT)
ALTER TABLE NHAHANG ADD CONSTRAINT FK_DG FOREIGN KEY (MADG) REFERENCES DANHGIA(MADG)

--Nhập dữ liệu cho các quan hệ
--NHA HANG
INSERT INTO NHAHANG VALUES('NH01','Sushi Ngon','Nhat Ban','VT01','DG01')
INSERT INTO NHAHANG VALUES('NH02','Tiem banh New York','My','VT03','DG02')
INSERT INTO NHAHANG VALUES('NH03','Tiem tra Hoang Gia','My','VT01','DG03')
INSERT INTO NHAHANG VALUES('NH04','Bun bo Hue','Viet Nam','VT01','DG04')


--VI TRI
INSERT INTO VITRI VALUES('VT01','Thu Duc','Ho Chi Minh')
INSERT INTO VITRI VALUES('VT02','Phu Nhuan','Ho Chi Minh')
INSERT INTO VITRI VALUES('VT03','Ba Dinh','Ha Noi')


-- DANH GIA
INSERT INTO DANHGIA VALUES('DG01',3.5,200000,1.531)
INSERT INTO DANHGIA VALUES('DG02',2.5,550000,324)
INSERT INTO DANHGIA VALUES('DG03',4.5,420000,83)
INSERT INTO DANHGIA VALUES('DG04',4.5,80000,815)


--3. Giá trung bình của các nhà hàng ở Ba Đình giá phải trên 50.000 đồng
-- 'TRIGGER'

--4. Thêm vào thuộc tính GHICHU có kiểu dữ liệu  varchar(40) cho quan hệ DANHGIA.
ALTER TABLE DANHGIA ADD GHICHU VARCHAR(40);

--5.In ra các nhà hàng (MANH,TENNH) phục vụ các món ăn của nền ẩm thực Mỹ.
SELECT MANH,TENNH
FROM NHAHANG
WHERE AMTHUC = 'My';

--6. In ra các nhà hàng (MANH,TENNH,DANHGIA,GIATB,SLDG) ở thành phố Hồ Chí Minh
--theo thứ tự tăng dần về đánh giá và giảm dần về giá trung bình.
SELECT NH.MANH,TENNH,DANHGIA, GIATB, SLDG
FROM NHAHANG NH, DANHGIA DG, VITRI VT
WHERE NH.MADG=DG.MADG
AND NH.MAVT = VT.MAVT
AND THANHPHO = 'Ho Chi Minh'
ORDER BY DANHGIA ASC, GIATB DESC;

--7.In ra vị trí (MAVT,QUAN,THANHPHO) không có nhà hàng nào được đánh giá.
SELECT MAVT, QUAN, THANHPHO
FROM VITRI
EXCEPT
SELECT VT.MAVT, QUAN, THANHPHO
FROM VITRI VT, NHAHANG NH, DANHGIA DG
WHERE VT.MAVT = NH.MAVT
AND DG.MADG=NH.MADG;


--8. In ra số lượng nhà hàng có giá trung bình trên 500.000 đồng và số lượng nhà hàng có giá trung bình dưới 500.000 đồng (SL_TREN,SL_DUOI)
SELECT *FROM
	(SELECT COUNT(MANH) 'SL_TREN' FROM NHAHANG NH, DANHGIA DG 
		WHERE NH.MADG = DG.MADG AND GIATB > 500000)
			AS DEMTREN, (SELECT COUNT(MANH) 'SL_DUOI' 
							FROM NHAHANG NH, DANHGIA DG WHERE NH.MADG = DG.MADG 
									AND GIATB < 500000) AS DEMDUOI;

